anguage: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="8eab5a94-4126-41a0-b023-dc2f5f158b99"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -dkimlana@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

